- name: "{{ desired_action }} Riak"
  become: true
  hosts: riakcs
  tasks:
    - service: name="riak" state={{ desired_state }}
  tags:
    - restart_riak
    - start_riak
    - stop_riak

- name: "{{ desired_action }} Stanchion"
  become: true
  hosts: stanchion
  tasks:
    - service: name="stanchion" state={{ desired_state }}
  tags:
    - restart_stanchion
    - start_stanchion
    - stop_stanchion

- name: "{{ desired_action }} Riak-CS"
  become: true
  hosts: riakcs
  tasks:
    - service: name="riak-cs" state={{ desired_state }}
  tags:
    - restart_riak-cs
    - start_riak-cs
    - stop_riak-cs