- name: Update {{ name }} admin.key
  lineinfile:
    dest: "{{ hostvars[inventory_hostname][name + '_conf'] }}"
    regexp: "^admin.key ?= ?.*$"
    line: "admin.key = {{ hostvars[riakcs_control].get('riak_key', 'not-set') }}"
    state: present
  notify: "restart {{ name }}"
  when: "'riak_key' in hostvars[riakcs_control] and 'riak_secret' in hostvars[riakcs_control]"

- name: Update {{ name }} admin.secret
  lineinfile:
    dest: "{{ hostvars[inventory_hostname][name + '_conf'] }}"
    regexp: "^admin.secret ?= ?.*$"
    line: "admin.secret = {{ hostvars[riakcs_control].get('riak_secret', 'not-set') }}"
    state: present
  notify: "restart {{ name }}"
  when: "'riak_key' in hostvars[riakcs_control] and 'riak_secret' in hostvars[riakcs_control]"
