---
dependencies:
  - role: common_installs
  - role: commcarehq
  - role: supervisor
  - {role: users, tags: users}
  - role: edit
  - {role: ksplice, tags: ksplice}
  - {role: newrelic, tags: newrelic, when: NEW_RELIC_KEY is defined}
