---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - pip install -r ansible/requirements.txt

script:
  - ansible-playbook -i dimagi/commcarehq-ansible/ansible/inventories/localhost dimagi/commcarehq-ansible/ansible/deploy_stack.yml --syntax-check
  - ansible-playbook -i dimagi/commcarehq-ansible/ansible/inventories/localhost dimagi/commcarehq-ansible/ansible/deploy_stack.yml -vvvv
