---
# deploy_production_webworker.yml
- name: Webworkers
  hosts: us-webworkers-production
  serial: 1
  vars:

    #- repository=fill me in with your git repo address!
    - deploy_env=production
    #- cchq_version= put a tag/branch name here, appropriate to your release naming
    #- app_name= the supervisorctl restart handler depends on this, can be replace once a supervisord roles is written so the config can be templated properly

  pre_tasks:

    - name: remove worker from load balancer
      delegate_to: "{{item}}"
      with_items: groups.us-proxy-production
      lineinfile:
        dest: /etc/apache2/sites-enabled/prod.conf
        #should change this to a regexp
        line: "        BalancerMember http://{{ansible_hostname}}:9010 loadfactor=2"
        state: absent

  post_tasks:

    # need to flesh out this task
    - name: add worker back to load balancer
      delegate_to: "{{item}}"
      with_items: groups.us-proxy-production
      lineinfile:
        dest: /etc/apache2/sites-enabled/prod.conf
        line: "        BalancerMember http://{{ansible_hostname}}:9010 loadfactor=2"
        insertbefore: "ProxySet lbmethod=byrequests"
        state: present

  roles:

    - webworker

