---

- name: Create PostgreSQL benchmark database
  sudo_user: postgres
  postgresql_db: name={{ item }} state=present
  with_items:
    - '{{ bench_db_name }}'

- name: Allow access to runner
  sudo_user: postgres
  lineinfile:
    dest: "{{ postgresql_config_home }}/pg_hba.conf"
    state: present
    line: "host bench postgres {{ groups['load_test_runner'][0] }}/32 trust"
    regexp: "{{ groups['load_test_runner'][0] }}"
  register: postgresql_access_updated

- name: Apply PostgreSQL configuration changes
  sudo_user: postgres
  service: name=postgresql state=restarted
  when: postgresql_access_updated.changed

- name: Install tsung dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - tsung_debian_pkgs
  tags:
    - tsung

- name: clone the github repository
  git:
    repo: https://github.com/processone/tsung.git
    dest: "{{ tsung_dest_dir }}"
    version: "{{ tsung_version }}"
  tags:
    - tsung

- name: configure
  shell: ./configure
  args:
    chdir: "{{ tsung_dest_dir }}"
    creates: "{{ tsung_dest_dir }}/config.status"
  tags:
    - tsung

- name: make
  shell: /usr/bin/make
  args:
    chdir: "{{ tsung_dest_dir}}"
    creates: "{{ tsung_dest_dir }}/ebin/tsung.app"
  tags:
    - tsung

- name: make install
  shell: /usr/bin/make install
  args:
    chdir: "{{ tsung_dest_dir }}"
  tags:
    - tsung
