---
# roles/apache2/handlers/main.yml

- name: Start Apache2 service
  sudo: yes
  service: name=apache2 state=started

- name: Stop Apache2 service
  sudo: yes
  service: name=apache2 state=stopped

- name: Restart Apache2 service
  sudo: yes
  service: name=apache2 state=restarted

- name: Reload Apache2 service
  sudo: yes
  service: name=apache2 state=reloaded
