- name: Make sure the CA certificates are available
  apt:
    pkg: ca-certificates
    state: present

- name: Update package list
  apt: update_cache=yes

- name: Install Barman
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  with_items:
    - barman

- name: Create Barman home directory
  file:
    path: '{{ barman_home }}'
    owner: "{{ barman_user }}"
    group: "{{ barman_user }}"
    mode: 0750
    state: directory

- name: Create Barman log directory
  file:
    path: '{{ barman_log_directory }}'
    owner: "{{ barman_user }}"
    group: "{{ barman_user }}"
    mode: 0750
    state: directory
