---
# roles/webworker/handlers/main.yml

- name: install pip requirements
  sudo: yes
  sudo_user: "{{cchq_user}}"
  with_items: cchq_requirements
  pip:
    requirements: "{{code_home}}/requirements/{{item}}"
    virtualenv: "{{virtualenv_home}}"

- name: copy localsettings
  sudo: yes
  sudo_user: "{{cchq_user}}"
  template:
    src: localsettings.py.j2
    dest: "{{code_home}}/localsettings.py"

- name: restart webworker app
  supervisorctl: name={{app_name}} state=restarted
