# These tasks are used to install Riak and RiakCS to the riakcs group
# Riak hosts their own apt repos and have scripts for installing that repo on debian machines
---
- name: Check if Riak is installed
  command: dpkg -s riak
  register: riak_deb_check
  failed_when: false
  changed_when: false

- name: Check if Riak CS is installed
  command: dpkg -s riak-cs
  register: riakcs_deb_check
  failed_when: false
  changed_when: false

- set_fact:
    riak_installed: "{{ riak_deb_check.rc == 0 }}"
    riakcs_installed: "{{ riakcs_deb_check.rc == 0 }}"

- name: Fetch Riak apt repo install script
  get_url: url={{ riak_script_url }} dest={{ riak_install_script }}
  when: not riak_installed

- name: Run Riak apt repo install script
  command: bash {{ riak_install_script }}
  when: not riak_installed

- name: Install riak from apt
  apt: name={{ riak_package }} state=present

- name: Fetch Riak CS apt repo install script
  get_url: url={{ riakcs_script_url }} dest={{ riakcs_install_script }}
  when: not riakcs_installed

- name: Run Riak CS apt repo install script
  command: bash {{ riakcs_install_script }}
  when: not riakcs_installed

- name: Install Riak CS from apt
  apt: name={{ riakcs_package }} state=present

- name: Create Riak data dir
  file:
    path: "{{ riak_data_dir }}"
    state: directory
    owner: "{{ riak_user }}"
    group: "{{ riak_user }}"

- name: Start Riak
  service: name=riak state=started enabled=yes

- name: Start RiakCS
  service: name=riak-cs state=started enabled=yes
