# More information on adding/removing nodes can be found here: http://docs.basho.com/riak/latest/ops/running/nodes/adding-removing/
#
# Joins nodes to the control node if:
#  - The node isn't a control node
#  - The node isn't already a member of the cluster
#
#  To setup stage the cluster but not commit use tags:
#  --tags=riakcs-cluster-prep
#
#  To stage and commit the cluster run:
#  --tags=riakcs-cluster
#
#  To just commit the staged cluster run:
#  --tags=riakcs-cluster-commit
#
#  To clear the staged commits run:
#  --tags=riakcs-cluster-clean

- set_fact:
    riakcs_control_short: "{{ riakcs_control.split('.')[0] }}"
  tags:
    - riakcs-cluster-prep
    - riakcs-cluster

- name: Join nodes to cluster
  command: "riak-admin cluster join riak-{{ riakcs_control_short }}@{{ riakcs_control }}"
  register: result
  tags:
    - riakcs-cluster-prep
    - riakcs-cluster
  when: "'{{ inventory_hostname }}' != '{{ riakcs_control }}'"

- debug: var=result.stdout

- name: Plan the changes
  command: "riak-admin cluster plan"
  register: result
  tags:
    - riakcs-cluster-prep
    - riakcs-cluster
  when: "'{{ inventory_hostname }}' != '{{ riakcs_control }}'"

- debug: var=result.stdout

- name: Commit the changes
  command: "riak-admin cluster commit"
  tags:
    - riakcs-cluster-commit
    - riakcs-cluster
  when: "'{{ inventory_hostname }}' != '{{ riakcs_control }}'"

- name: Clear any staged commits
  command: "riak-admin cluster clear"
  tags:
    - riakcs-cluster-clean
  when: "'{{ inventory_hostname }}' != '{{ riakcs_control }}'"
