# Write admin.key and admin.secret in configuration file

- name: Update {{ service }} admin.key
  lineinfile:
    dest: "{{ path }}"
    regexp: "^admin.key ?= ?.*$"
    line: "admin.key = {{ hostvars[riakcs_control].get('riak_key', 'not-set') }}"
    state: present
  notify: "restart {{ service }}"

- name: Update {{ service }} admin.secret
  lineinfile:
    dest: "{{ path }}"
    regexp: "^admin.secret ?= ?.*$"
    line: "admin.secret = {{ hostvars[riakcs_control].get('riak_secret', 'not-set') }}"
    state: present
  notify: "restart {{ service }}"
