- name: Update Riak CS admin.key
  replace:
    dest: "{{ riakcs_dest }}/{{ riakcs_conf }}"
    regexp: "^admin.key.*$"
    replace: "admin.key = {{ riak_key }}"
    backup: yes
  tags: riakcs-admin-keys

- name: Update Riak CS admin.secret
  replace:
    dest: "{{ riakcs_dest }}/{{ riakcs_conf }}"
    regexp: "^admin.secret.*$"
    replace: "admin.secret = {{ riak_secret }}"
    backup: yes
  tags: riakcs-admin-keys
