# Base env containing default values which get
# overridden or added to in each of the specific envs below.
---
base:
  sudo_user: cchq
  django_bind: 0.0.0.0
  django_port: 9010
  flower_port: 5555
  home: "/home/cchq"
  project: commcare-hq
  code_repo: 'git://github.com/dimagi/commcare-hq.git'
  timing_log: null  # make a file path to log deploy timing to it. e.g. '../fabric-timing.txt'
  jython_memory: "3584m"
  formplayer_memory: "3584m"
  keepalive: 60

development:

  # parameters for configuring the celery worker processes
  celery_processes:
    '*':
      main:
        concurrency: 1
      background_queue:
        concurrency: 1
      periodic:
        concurrency: 1
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 1
      reminder_queue:
        concurrency: 1
      reminder_rule_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 1
      sms_queue:
        concurrency: 1
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 4
      logistics_reminder_queue:
        concurrency: 1
      logistics_background_queue:
        concurrency: 1
      flower: {}

india:
  environment: india

  celery_processes:
    '*':
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      flower: {}

softlayer:
  environment: softlayer

  celery_processes:
    '*':
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 3
      async_restore_queue:
        concurrency: 4
      flower: {}

production:
  environment: production

  celery_processes:
    hqcelery0:
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 50
      ucr_queue:
        concurrency: 4
    hqcelery1:
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      logistics_reminder_queue:
        concurrency: 2
      logistics_background_queue:
        concurrency: 2
      async_restore_queue:
        concurrency: 4
      flower: {}

staging:
  environment: staging

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      pillow_retry_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}

zambia:
  environment: zambia

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 4
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 4
      ucr_queue:
        concurrency: 2
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}

swiss:
  environment: swiss
  jython_memory: "1024m"
  formplayer_memory: "1024m"

  celery_processes:
    '*':
      main:
        concurrency: 1
      background_queue:
        concurrency: 1
      periodic:
        concurrency: 1
      repeat_record_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 1
      pillow_retry_queue:
        concurrency: 1
      ucr_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 1
      reminder_queue:
        concurrency: 1
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}

tsung:
  environment: tsung
  jython_memory: "1024m"
  formplayer_memory: "1024m"

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      pillow_retry_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      flower: {}
