# Base env containing default values which get
# overridden or added to in each of the specific envs below.
---
base:
  sudo_user: cchq
  django_bind: 0.0.0.0
  django_port: 9010
  flower_port: 5555
  gunicorn_workers_factor: 1
  gunicorn_workers_static_factor: 0
  home: "/home/cchq"
  project: commcare-hq
  code_repo: 'git://github.com/dimagi/commcare-hq.git'
  timing_log: null  # make a file path to log deploy timing to it. e.g. '../fabric-timing.txt'
  jython_memory: "3584m"
  formplayer_memory: "3584m"
  keepalive: 60
  http_proxy: null
  newrelic_javaagent: False

softlayer:
  environment: softlayer
  formplayer_memory: "7000m"
  newrelic_javaagent: True
  celery_processes:
    '10.162.36.233':  # celery0
      periodic:
        server_whitelist: '10.162.36.233'
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 200
      ucr_queue:
        concurrency: 4
      ucr_indicator_queue:
        concurrency: 1
      main:
        concurrency: 8
      saved_exports_queue:
        concurrency: 3
    '10.162.36.194':  # celery1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 8
      async_restore_queue:
        concurrency: 8
      background_queue:
        concurrency: 4
      flower: {}
  pillows:
    '*':
      AppDbChangeFeedPillow:
        num_processes: 1
      ApplicationBlobDeletionPillow:
        num_processes: 1
      ApplicationToElasticsearchPillow:
        num_processes: 1
      BlobDeletionPillow:
        num_processes: 1
      CacheInvalidatePillow:
        num_processes: 1
      CaseSearchToElasticsearchPillow:
        num_processes: 1
      CaseToElasticsearchPillow:
        num_processes: 1
      DefaultChangeFeedPillow:
        num_processes: 1
      DomainDbKafkaPillow:
        num_processes: 1
      FormSubmissionMetadataTrackerPillow:
        num_processes: 1
      GroupPillow:
        num_processes: 1
      GroupToUserPillow:
        num_processes: 1
      kafka-ucr-main:
        num_processes: 1
      kafka-ucr-static:
        num_processes: 1
      KafkaDomainPillow:
        num_processes: 1
      LedgerToElasticsearchPillow:
        num_processes: 1
      ReportCaseToElasticsearchPillow:
        num_processes: 1
      ReportXFormToElasticsearchPillow:
        num_processes: 1
      SqlSMSPillow:
        num_processes: 1
      UnknownUsersPillow:
        num_processes: 1
      UpdateUserSyncHistoryPillow:
        num_processes: 1
      UserCacheInvalidatePillow:
        num_processes: 1
      UserGroupsDbKafkaPillow:
        num_processes: 1
      UserPillow:
        num_processes: 1
      XFormToElasticsearchPillow:
        num_processes: 1


icds:
  environment: icds
  http_proxy: 10.247.24.16:3128
  additional_no_proxy_hosts: "relay.nic.in,smsgw.sms.gov.in,icds-cas.gov.in"
  gunicorn_workers_factor: 2
  formplayer_memory: "16000m"
  gunicorn_workers_static_factor: 1
  celery_processes:
    '10.247.24.19': # celery0
      main:
        concurrency: 8
      periodic:
        concurrency: 4
        server_whitelist: 10.247.24.19
      pillow_retry_queue:
        concurrency: 1
      repeat_record_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 4
      background_queue:
        concurrency: 4
      reminder_case_update_queue:
        concurrency: 10
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      email_queue:
        concurrency: 2
      async_restore_queue:
        concurrency: 4
      ucr_indicator_queue:
        concurrency: 8
      flower: {}
    '10.247.24.31': # celery1
      ucr_indicator_queue:
        concurrency: 12
  pillows:
    '10.247.24.20': # pillow0
      AppDbChangeFeedPillow:
        num_processes: 1
      ApplicationBlobDeletionPillow:
        num_processes: 1
      ApplicationToElasticsearchPillow:
        num_processes: 1
      BlobDeletionPillow:
        num_processes: 1
      CacheInvalidatePillow:
        num_processes: 1
      DefaultChangeFeedPillow:
        num_processes: 1
      DomainDbKafkaPillow:
        num_processes: 1
      GroupPillow:
        num_processes: 1
      GroupToUserPillow:
        num_processes: 1
      kafka-ucr-static-awc-location:
        num_processes: 1
      kafka-ucr-static-cases:
        num_processes: 8
      kafka-ucr-static-ccs_record_cases:
        num_processes: 8
      kafka-ucr-static-ccs_record_cases_monthly:
        num_processes: 8
      kafka-ucr-static-child_cases_monthly:
        num_processes: 8
      kafka-ucr-static-child_health_cases:
        num_processes: 8
      kafka-ucr-static-person_cases:
        num_processes: 8
      kafka-ucr-static-test:
        num_processes: 1
    '10.247.24.30': # pillow1
      CaseToElasticsearchPillow:
        num_processes: 1
      FormSubmissionMetadataTrackerPillow:
        num_processes: 1
      kafka-ucr-static-forms:
        num_processes: 8
      kafka-ucr-main:
        num_processes: 2
      KafkaDomainPillow:
        num_processes: 1
      LedgerToElasticsearchPillow:
        num_processes: 1
      SqlSMSPillow:
        num_processes: 1
      UnknownUsersPillow:
        num_processes: 1
      UpdateUserSyncHistoryPillow:
        num_processes: 1
      UserCacheInvalidatePillow:
        num_processes: 1
      UserGroupsDbKafkaPillow:
        num_processes: 1
      UserPillow:
        num_processes: 1
      XFormToElasticsearchPillow:
        num_processes: 1


production:
  environment: production
  newrelic_javaagent: True

  celery_processes:
    hqcelery0:
      periodic:
        server_whitelist: hqcelery0.internal-va.commcarehq.org
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 200
      ucr_queue:
        concurrency: 4
      ucr_indicator_queue:
        concurrency: 1
    hqcelery1:
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 8
      logistics_reminder_queue:
        concurrency: 2
      logistics_background_queue:
        concurrency: 2
      async_restore_queue:
        concurrency: 4
      flower: {}
    hqcelery2:
      main:
        concurrency: 8
      saved_exports_queue:
        concurrency: 4
      background_queue:
        concurrency: 4
  pillows:
    '*':
      AppDbChangeFeedPillow:
        num_processes: 1
      ApplicationBlobDeletionPillow:
        num_processes: 1
      ApplicationToElasticsearchPillow:
        num_processes: 1
      BlobDeletionPillow:
        num_processes: 1
      CacheInvalidatePillow:
        num_processes: 1
      CaseSearchToElasticsearchPillow:
        num_processes: 1
      CaseToElasticsearchPillow:
        num_processes: 1
      DefaultChangeFeedPillow:
        num_processes: 1
      DomainDbKafkaPillow:
        num_processes: 1
      FarmerRecordFluffPillow:
        num_processes: 1
      FormSubmissionMetadataTrackerPillow:
        num_processes: 1
      GeographyFluffPillow:
        num_processes: 1
      GroupPillow:
        num_processes: 1
      GroupToUserPillow:
        num_processes: 1
      IntraHealthFormFluffPillow:
        num_processes: 1
      kafka-ucr-main-08:
        num_processes: 1
      kafka-ucr-main-9f:
        num_processes: 1
      kafka-ucr-static:
        num_processes: 1
      KafkaDomainPillow:
        num_processes: 1
      LedgerToElasticsearchPillow:
        num_processes: 1
      M4ChangeFormFluffPillow:
        num_processes: 1
      OpmUserFluffPillow:
        num_processes: 1
      RecouvrementFluffPillow:
        num_processes: 1
      ReportCaseToElasticsearchPillow:
        num_processes: 1
      ReportXFormToElasticsearchPillow:
        num_processes: 1
      SqlSMSPillow:
        num_processes: 1
      UCLAPatientFluffPillow:
        num_processes: 1
      UnknownUsersPillow:
        num_processes: 1
      UpdateUserSyncHistoryPillow:
        num_processes: 1
      UserCacheInvalidatePillow:
        num_processes: 1
      UserGroupsDbKafkaPillow:
        num_processes: 1
      UserPillow:
        num_processes: 1
      WorldVisionChildFluffPillow:
        num_processes: 1
      WorldVisionHierarchyFluffPillow:
        num_processes: 1
      WorldVisionMotherFluffPillow:
        num_processes: 1
      XFormToElasticsearchPillow:
        num_processes: 1

staging:
  environment: staging

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      pillow_retry_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}
  pillows:
    '*':
      AppDbChangeFeedPillow:
        num_processes: 1
      ApplicationBlobDeletionPillow:
        num_processes: 1
      ApplicationToElasticsearchPillow:
        num_processes: 1
      BlobDeletionPillow:
        num_processes: 1
      CacheInvalidatePillow:
        num_processes: 1
      CaseSearchToElasticsearchPillow:
        num_processes: 1
      CaseToElasticsearchPillow:
        num_processes: 1
      DefaultChangeFeedPillow:
        num_processes: 1
      DomainDbKafkaPillow:
        num_processes: 1
      FormSubmissionMetadataTrackerPillow:
        num_processes: 1
      GroupPillow:
        num_processes: 1
      GroupToUserPillow:
        num_processes: 1
      kafka-ucr-main:
        num_processes: 1
      kafka-ucr-static:
        num_processes: 1
      KafkaDomainPillow:
        num_processes: 1
      LedgerToElasticsearchPillow:
        num_processes: 1
      ReportCaseToElasticsearchPillow:
        num_processes: 1
      ReportXFormToElasticsearchPillow:
        num_processes: 1
      SqlSMSPillow:
        num_processes: 1
      UnknownUsersPillow:
        num_processes: 1
      UpdateUserSyncHistoryPillow:
        num_processes: 1
      UserCacheInvalidatePillow:
        num_processes: 1
      UserGroupsDbKafkaPillow:
        num_processes: 1
      UserPillow:
        num_processes: 1
      XFormToElasticsearchPillow:
        num_processes: 1

swiss:
  environment: swiss
  jython_memory: "1024m"
  formplayer_memory: "1024m"

  service_blacklist:
    - supervisor_websockets.conf

  celery_processes:
    '*':
      main:
        concurrency: 1
      background_queue:
        concurrency: 1
      periodic:
        concurrency: 1
        server_whitelist: swiss.commcarehq.org
      repeat_record_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 1
      pillow_retry_queue:
        concurrency: 1
      ucr_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 1
      reminder_queue:
        concurrency: 1
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}
  pillows:
    '*':
      AppDbChangeFeedPillow:
        num_processes: 1
      ApplicationBlobDeletionPillow:
        num_processes: 1
      ApplicationToElasticsearchPillow:
        num_processes: 1
      BlobDeletionPillow:
        num_processes: 1
      CacheInvalidatePillow:
        num_processes: 1
      CaseToElasticsearchPillow:
        num_processes: 1
      DefaultChangeFeedPillow:
        num_processes: 1
      DomainDbKafkaPillow:
        num_processes: 1
      FormSubmissionMetadataTrackerPillow:
        num_processes: 1
      GroupPillow:
        num_processes: 1
      GroupToUserPillow:
        num_processes: 1
      KafkaDomainPillow:
        num_processes: 1
      SqlSMSPillow:
        num_processes: 1
      UnknownUsersPillow:
        num_processes: 1
      UpdateUserSyncHistoryPillow:
        num_processes: 1
      UserCacheInvalidatePillow:
        num_processes: 1
      UserGroupsDbKafkaPillow:
        num_processes: 1
      UserPillow:
        num_processes: 1
      XFormToElasticsearchPillow:
        num_processes: 1
