- template: src={{ item }}.yaml.j2 dest=/etc/dd-agent/conf.d/{{ item }}.yaml
  notify: restart datadog
  tags:
    - datadog_integrations
  with_items: "{{ datadog_integrations }}"
  when: datadog_integrations is defined
