---
- name: Install ecryptfs-utils
  sudo: yes
  apt:
    name: ecryptfs-utils

- name: Check for already mounted drive
  shell: cat /etc/fstab
  register: fstab_contents

- name: Create /opt/data directory
  sudo: yes
  file: path=/opt/data owner=root group=root mode=0770 state=directory

- name: Add encryption password to keyring
  sudo: yes
  shell: 'printf "%s" "{{ encrypted_drive_password }}" | ecryptfs-add-passphrase | grep -o "\[.*\]" | sed "s/\[//g;s/\]//g"'
  register: password_hash
  when: "'/opt/data' not in fstab_contents.stdout"

- name: Mount data drive
  sudo: yes
  shell: "mount -t ecryptfs -o key=passphrase:passphrase_passwd={{ encrypted_drive_password }},user,noauto,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_unlink_sigs,ecryptfs_enable_filename_crypto=y,ecryptfs_fnek_sig={{ password_hash.stdout }},verbosity=0 /opt/data/ /opt/data/"
  when: "'/opt/data' not in fstab_contents.stdout"

- name: Drop unencrypted readme in directory
  sudo: yes
  lineinfile:
    dest: '/opt/data/README'
    line: 'If you can read this file the directory is unencrypted'
    create: yes
    owner: root
    group: root
    mode: 0770

- name: Register mount configuration
  sudo: yes
  shell: "tail /etc/mtab -n1"
  register: mount_configuration

- name: Create entry in fstab
  sudo: yes
  lineinfile: 
    dest: "/etc/fstab"
    regexp: "^/opt/data"
    backup: yes
    line: "{{ mount_configuration.stdout }}"
  when: "'/opt/data' not in fstab_contents.stdout"
