shared_data_dir: /opt/shared_data
shared_dir_gid: 1500  # This GID cannot already be allocated
shared_dir_groupname: nfs

restore_payload_dir: "{{ shared_data_dir }}/restore_payloads"
transfer_payload_dir: "{{ shared_data_dir }}/{{ transfer_payload_dir_name }}"
