# Tasks to be run on machines running django

- name: Create payload purging cron job
  sudo: yes
  cron:
    name: "Purge old restore payload files"
    special_time: daily
    job: "find {{ restore_payload_dir }} -name \"*.xml\" -maxdepth 1 -mtime +4 -delete"
    user: root
