# Tasks to be run on machines running django

- name: create restore payloads directory
  sudo: yes
  file:
    path: "{{ restore_payload_dir }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0755
    state: directory

- name: Create payload purging cron job
  sudo: yes
  cron:
    name: "Purge old restore payload files"
    special_time: daily
    job: "find {{ restore_payload_dir }} -name \"*.xml\" -maxdepth 1 -mtime +4 -delete"
    user: "{{ cchq_user }}"
  tags:
    - restore
