---
# roles/webworker/tasks/main.yml

- name: Run syncdb
  sudo_user: "{{ cchq_user }}"
  django_manage:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    command: syncdb

- name: Pre-migrate apps
  sudo_user: "{{ cchq_user }}"
  django_manage:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    command: "migrate {{ item }}"
  with_items:
    - ilsgateway 0001 --fake

- name: Migrate apps
  sudo_user: "{{ cchq_user }}"
  django_manage:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    command: migrate

- name: Collect static files
  sudo_user: "{{ cchq_user }}"
  django_manage:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    command: collectstatic

- include_vars: "{{ deploy_env }}_supervisor_tasks.yml"
- include: ../../supervisor/tasks/supervised_tasks.yml
