---

 - name: Add Citus apt key
   apt_key: 
    url: " {{ citus_apt_key_url }}"
    state: present
    
 - name: Add Citus apt repo
   apt_repository: 
    repo: "{{ citus_apt_repo }}"
    state: present
   register: add_citus_repo

 - name: Update package list
   apt: 
    update_cache: yes
   when: add_citus_repo is changed

 - name: Install Citus
   apt: 
    name: "{{citus_binary}}"
    state: present

 - name: Add citus to postgres prelod libraries
   shell: "pg_conftool 11 main set shared_preload_libraries 'citus, pg_stat_statements'"
   become: yes
   notify: Restart postgres

 - name: Add Citus Extension on Coordinator Database
   become: yes
   become_user: postgres
   postgresql_ext:
     name: citus
     db: "{{ item.name }}"
   with_items: "{{ postgresql_dbs.all }}"
   when: item.host == inventory_hostname
   tags:
    - configure

 - name: Set up Citus Worker DBs
   import_tasks: setup_worker.yml
   tags:
     - configure

 - name: Setup citusdb_master
   import_tasks: setup_cordinator.yml 
   tags:
    - configure
