---
 - name: Add Workers Nodes to the Cordinator
   become: yes
   become_user: postgres
   shell: psql {{ item.0.name }} -c "SELECT * from master_add_node( '{{item.1|ipaddr}}' , 5432) ; "
  #  debug:
  #    msg: " {{ item.0.name }} {{item.1|ipaddr}} "
   with_nested: 
    - "{{ postgresql_dbs.all }}"
    - "{{groups['citusdb_worker']}}"
   when: inventory_hostname in groups["citusdb_cordinator"]  and (item.0.host in groups["citusdb_cordinator"])
   tags:
    - citusdb
    - citusdb_cordinator