cchq_home: /home/{{ cchq_user }}
www_dir: "{{ cchq_home }}/www"
www_home: "{{ www_dir }}/{{ deploy_env }}"
code_home: "{{ www_home }}/code_root"
preindex_home: "{{ www_home }}/code_root_preindex"
log_home: "{{ www_home }}/log"
service_home: "{{ cchq_home }}/services"
virtualenv_home: "{{ www_home }}/python_env"
virtualenv_preindex_home: "{{ www_home }}/python_env_preindex"

shared_dir_gid: 1500  # This GID cannot already be allocated
shared_mount_dir: "/mnt/shared_data"
transfer_payload_dir_name: "transfer_payloads"
public_site_path: /opt/commcare-hq-public/site/output
commtrack_public_site_path: /opt/commtrack-static/site/output/
cchq_user: cchq
dev_group: dev

django_port: 9010
