cchq_home: /home/{{ cchq_user }}
www_dir: "{{ cchq_home }}/www"
www_home: "{{ www_dir }}/{{ deploy_env }}"
code_home: "{{ www_home }}/code_root"
preindex_home: "{{ www_home }}/code_root_preindex"
log_home: "{{ www_home }}/log"
service_home: "{{ cchq_home }}/services"
virtualenv_home: "{{ www_home }}/python_env"
virtualenv_preindex_home: "{{ www_home }}/python_env_preindex"
restore_payload_dir: "{{ www_home }}/data/restore_payloads"

cchq_user: cchq
dev_group: dev

django_port: 9010
