---
# tasks file for zabbix_common

- name: Make zabbix external scripts directory
  sudo: yes
  file:
    path: '{{ zabbix_external_scripts_dir }}'
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory

- name: Make zabbix user param directory
  sudo: yes
  file:
    path: '{{ zabbix_user_parm_dir }}'
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory

- name: Install diskstats conf
  sudo: yes
  template:
    src: userparameter_diskstats.conf.j2
    dest: '{{ zabbix_user_parm_dir }}/userparameter_diskstats.conf'
    mode: 0644
  notify: restart zabbix_agentd

- name: Install lld-disks script
  sudo: yes
  copy:
    src: 'lld-disks.py'
    dest: '{{ zabbix_external_scripts_dir }}/lld-disks.py'
    mode: 0755
  notify: restart zabbix_agentd
