---
# tasks file for zabbix_common

- name: Install diskstats conf
  sudo: yes
  copy:
    src: 'userparameter_diskstats.conf'
    dest: '/etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf'
    mode: 0644
  notify: restart zabbix_agentd

- name: Install diskstats conf
  sudo: yes
  copy:
    src: 'lld-disks.py'
    dest: '/usr/local/bin/lld-disks.py'
    mode: 0755
  notify: restart zabbix_agentd
