---
- name: Add nodes
  uri:
    url: "http{% if couchdb_secure %}s{% endif %}://{{ inventory_hostname|ipaddr }}:{{ couchdb_node_conf_port }}/_nodes/couchdb@{{ item|ipaddr }}"
    method: PUT
    user: "{{ couchdb2.username }}"
    password: "{{ couchdb2.password }}"
    force_basic_auth: true
    status_code: 200, 409 # 409 means already set up (conflict)
    body: '{}'
  when: inventory_hostname == groups.couchdb2.0 and item != groups.couchdb2.0
  with_items: "{{ groups.couchdb2 }}"
