---
- name: set couchdb username and password
  uri:
    url: "http{% if couchdb_secure %}s{% endif %}://{{ inventory_hostname|ipaddr }}:{{ couchdb_conf_port }}/_node/couchdb@{{ inventory_hostname|ipaddr }}/_config/admins/{{ couchdb2.username }}"
    method: PUT
    status_code: 200, 401 # 401 means this is already set up
    body: '"{{ couchdb2.password }}"'
    body_format: raw

- name: Add nodes
  uri:
    url: "http{% if couchdb_secure %}s{% endif %}://{{ inventory_hostname|ipaddr }}:{{ couchdb_node_port }}/_nodes/couchdb@{{ item|ipaddr }}"
    method: PUT
    user: "{{ couchdb2.username }}"
    password: "{{ couchdb2.password }}"
    force_basic_auth: true
    status_code: 200, 409 # 409 means already set up (conflict)
    body: '{}'
  when: inventory_hostname == groups.couchdb2.0 and item != groups.couchdb2.0
  with_items: "{{ groups.couchdb2 }}"
