---
- name: set couchdb username and password
  uri:
    url: "http{% if couchdb_secure %}s{% endif %}://{{ inventory_hostname|ipaddr }}:{{ couchdb_port }}/_node/couchdb@{{ inventory_hostname|ipaddr }}/_config/admins/{{ couchdb2.username }}"
    method: PUT
    status_code: 200, 401 # 401 means this is already set up
    body: '"{{ couchdb2.password }}"'
    body_format: raw

- name: Add nodes
  uri:
    url: "http{% if couchdb_secure %}s{% endif %}://{{ inventory_hostname|ipaddr }}:{{ couchdb_node_port }}/_nodes/couchdb@{{ item|ipaddr }}"
    method: PUT
    user: "{{ couchdb2.username }}"
    password: "{{ couchdb2.password }}"
    force_basic_auth: true
    status_code: 200, 409 # 409 means already set up (conflict)
    body: '{}'
  when: inventory_hostname == groups.couchdb2.0 and item != groups.couchdb2.0
  with_items: "{{ groups.couchdb2 }}"

- name: Copy couch restart script
  sudo: yes
  template:
    src: "couch2-restarter.sh.j2"
    dest: "/usr/local/sbin/couch2-restarter.sh"
    group: root
    owner: root
    mode: 0700
    backup: yes
  tags:
    - cron

- name: Create Cron job
  sudo: yes
  cron:
    name: "Reboot Couch"
    job: "/usr/local/sbin/couch2-restarter.sh > /dev/null"
    user: root
    cron_file: couch2-restarter
  tags:
    - cron

- name: Copy couch backup script
  sudo: yes
  template:
    src: "create_couchdb_backup.sh.j2"
    dest: "/usr/local/sbin/create_couchdb_backup.sh"
    group: couchdb
    owner: couchdb
    mode: 0700
    backup: yes
  when: backup_couch
  tags:
    - cron
    - backup

- name: Create Daily Cron job
  sudo: yes
  cron:
    name: "Backup blobdb daily"
    job: "/usr/local/sbin/create_couchdb_backup.sh daily 3"
    minute: 0
    hour: "{{ nadir_hour|default(0) }}"
    weekday: "1,2,3,4,5,6"
    user: couchdb
    cron_file: backup_couch
  when: backup_couch
  tags:
    - cron

- name: Create Weekly Cron job
  sudo: yes
  cron:
    name: "Backup blobdb weekly"
    job: "/usr/local/sbin/create_couchdb_backup.sh weekly 21"
    minute: 0
    hour: "{{ nadir_hour|default(0) }}"
    weekday: 0
    user: couchdb
    cron_file: backup_couch
  when: backup_couch
  tags:
    - cron
    - backup
