deploy_env: icds-staging
env_monitoring_id: icds-staging
users:
  - dimagi
  - fissionlabs
slack_alerts_channel: icds-staging
git_repositories:
  - url: git@github.com:dimagi/commcare-icds.git
    dest: icds
    deploy_key: deploy_key.pem
deploy_keys:
  deploy_key.vault: deploy_key.pem
