
- name: Install sentry dependencies
  apt: 
    name: 
      - libxmlsec1-dev
      - pkg-config
      - supervisor
    state: present 
  
- name: create sentry user
  user: 
    name=sentry
    state=present
    createhome=yes

- name: clear users password valid time
  shell: chage -M -1 sentry

- name: Create virtualenv and config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sentry_virtualenv_path }}"
    - "{{ sentry_app_config }}"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip2

- name: Create virtual env for sentry
  pip:
    name: sentry=={{ sentry_version }}
    virtualenv: "{{ sentry_virtualenv_path }}"
    virtualenv_command: virtualenv


- name: Copy sentry config files
  template:
    src: sentry.conf.py.j2
    dest: "{{ sentry_app_config }}/sentry.conf.py"
  
- name: Copy sentry config files
  template:
    src: config.yml.j2
    dest: "{{ sentry_app_config }}/config.yml"
 
- name: Create supervisor file
  template:
    src: sentry_web_server.conf.j2
    dest: "/etc/supervisor/conf.d/sentry_web_service.conf"
  notify: restart supervisor