---

- name: install supervisor
  apt: name=supervisor state=present update_cache=true
  sudo: yes

- name: configure supervisor
  template: src=supervisord.conf.j2 dest={{ supervisor_conf_home }}/supervisord.conf
  sudo: yes
  register: supervisor_configured

- name: make supervisor task home
  sudo: yes
  file: path={{ supervisor_task_conf }} state=directory owner={{ cchq_user }}

- name: apply configuration changes
  debug: msg="Stopping supervisor to pick up configuration changes"
  when: supervisor_configured.changed
  sudo: yes
  sudo_user: "{{ cchq_user }}"
  notify:
    - stop supervisor
    - start supervisor
