# Possible values for riak_backend
#
# - "leveldb"
#   The default, use this unless you know you need something different.
#   Requires less RAM, lower performance.
#
# - "bitcask"
#   Keeps all keys in RAM, higher performance, but crashes if it does not have
#   enough RAM.
#
# - "leveldb-bad-config"
#   Bad leveldb configuration. We're slowly migrating away from this, but the
#   migration requires reading each object from the old cluster and saving
#   it in a new cluster.
#   http://lists.basho.com/pipermail/riak-users_lists.basho.com/2017-March/019142.html
#
riak_backend: "leveldb"

# `riakcs_port` is defined in group_vars/all.yml

riak_port: 8087
riak_data_root_leveldb: "{{ riak_data_dir }}/leveldb"
riak_data_root_blocks: "{{ riak_data_dir }}/blocks"
riak_data_dir: "{{ encrypted_root }}/riak"
riak_ring_dir: "{{ riak_data_dir }}/ring"
riak_nodename: "riak@{{ inventory_hostname }}"
riak_ring_size: 128

riakcs_ebin: "/usr/lib/riak-cs/lib/riak_cs-{{ riakcs_version }}/ebin"

stanchion_port: 8085
stanchion_data_dir: "{{ encrypted_root }}/stanchion"
