- name: install newrelic plugin agent
  pip: name=newrelic-plugin-agent
  pip: name=newrelic-plugin-agent[postgresql]

- name: make newrelic config directory
  file:
    path: /etc/newrelic
    state: directory

- name: copy newrelic plugin agent config
  template:
    src: newrelic-plugin-agent.cfg.j2
    dest: /etc/newrelic/newrelic-plugin-agent.cfg
  register: newrelic_plugin_agent_config

- name: copy newrelic plugin agent startup script
  command: cp /opt/newrelic-plugin-agent/newrelic-plugin-agent.deb /etc/init.d/newrelic-plugin-agent
  args:
    creates: /etc/init.d/newrelic-plugin-agent

- name: make newrelic plugin agent startup script executible
  file:
    path: /etc/init.d/newrelic-plugin-agent
    mode: "u=rwx,g=rx,o=rx"

- name: make newrelic plugin agent directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /var/run/newrelic
    - /var/log/newrelic

- name: Make sure newrelic plugin agent has started
  service: name=newrelic-plugin-agent state=started

- name: Restart newrelic plugin agent
  service: name=newrelic-plugin-agent state=restarted
  when: newrelic_plugin_agent_config.changed
