- name: Touchforms user
  delegate_to: "{{ groups.webworkers.0 }}"
  sudo_user: "{{ cchq_user }}"
  django_user:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    state: present
    name: "{{ settings.touchforms.user.username }}"
    password: "{{ settings.touchforms.user.password }}"
    superuser: yes

- name: Copy Jython localsettings.py
  sudo: yes
  template:
    src: localsettings.py.j2
    dest: "{{ code_home }}/submodules/touchforms-src/touchforms/backend/localsettings.py"
    group: cchq
    owner: cchq
    mode: 0644

- include_vars: "{{ deploy_env }}_supervisor_tasks.yml"
- include: ../../supervisor/tasks/supervised_tasks.yml
