- name: Touchforms user
  delegate_to: "{{ groups.webworkers.0 }}"
  sudo_user: "{{ cchq_user }}"
  django_user:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    state: present
    name: "{{ localsettings.TOUCHFORMS_API_USER }}"
    password: "{{ localsettings.TOUCHFORMS_API_PASSWORD }}"
    superuser: yes

- name: Copy Jython localsettings.py
  sudo: yes
  template:
    src: localsettings.py.j2
    dest: "{{ code_home }}/submodules/touchforms-src/touchforms/backend/localsettings.py"
    group: cchq
    owner: cchq
    mode: 0644

- name: Create session purging cron job
  sudo: yes
  cron:
    name: "Purge old touchforms sessions"
    special_time: daily
    job: "find {{ touchforms_data_dir }} -maxdepth 1 -mtime +90 -delete"
    user: root
    cron_file: ../crontab

#- include_vars: "supervisor_tasks.yml"
#- include: ../../supervisor/tasks/supervised_tasks.yml
