---
# Install base packages, common to all servers
- name: Install common packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - libxml2-dev
    - libxslt1-dev
    - git
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils
    - npm

- name: Set NPM registry
  command: 'npm config set registry http://registry.npmjs.org/'
  sudo: yes

- name: Install npm lessc
  npm: name={{ item }} state=present global=yes
  sudo: yes
  with_items:
    - less@1.3.1

- name: Install lessc from source
  sudo: yes
  # this is lessc 1.7.3
  git: repo='https://github.com/less/less.js' dest='/opt/lessc' version='546bedd3' recursive=yes accept_hostkey=yes depth=1

- name: Install pip packages
  pip: name={{ item }}
  sudo: yes
  with_items:
    - fabric
    - virtualenv
    - sh
