---
# Install base packages, common to all servers
- name: Install common packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - libxml2-dev
    - libxslt1-dev
    - git
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils

- name: Install pip packages
  pip: name={{ item }}
  sudo: yes
  with_items:
    - fabric
    - virtualenv
    - sh
