- include_vars: "../../../../environments/{{ deploy_env }}/app-processes.yml"
  tags:
    - services

- name: define reminder queue services
  become: cchq
  template:
    src: "../templates/{{ item }}"
    dest: "{{ service_home }}/{{ deploy_env }}_{{ item }}"
  when: celery_processes.get(ansible_hostname).reminder_queue is defined
  items:
    - supervisor_reminder_queue.conf
    - supervisor_queue_schedule_instances.conf
    - supervisor_handle_survey_actions.conf
  tags:
    - services

- name: define submission reprocessing queue services
  become: cchq
  template:
    src: "../templates/supervisor_submission_reprocessing_queue.conf"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_submission_reprocessing_queue.conf"
  when: celery_processes.get(ansible_hostname).submission_reprocessing_queue is defined
  tags:
    - services

- name: define pillow retry queue services
  become: cchq
  template:
    src: "../templates/supervisor_pillow_retry_queue.conf"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_pillow_retry_queue.conf"
  when: celery_processes.get(ansible_hostname).pillow_retry_queue is defined
  tags:
    - services

- name: define pillow retry queue services
  become: cchq
  template:
    src: "../templates/supervisor_sms_queue.conf"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_sms_queue.conf"
  when: celery_processes.get(ansible_hostname).sms_queue is defined
  tags:
    - services

- name: define errand boy services
  become: cchq
  template:
    src: "../templates/supervisor_errand_boy.conf"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_errand_boy.conf"
  tags:
    - services
