# If "pull CommCare HQ source" fails with any of these messages
# - fatal: destination path '/home/cchq/www/dev/code_root' already exists and is not an empty directory.
# - /home/cchq/www/dev/code_root/.git: Permission denied
# Uncomment these lines
#- name: delete staticfiles
#  become: yes
#  file:
#    path: "{{ code_home }}"
#    state: absent

- name: create required directories
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ www_dir }}"
    - "{{ www_home }}"
    - "{{ log_home }}"
    - "{{ code_releases }}"

# Do not update source unless you're cloning for the first time

- name: register git repo
  stat: path="{{ code_home }}/.git"
  register: gitdir

- block:
    - name: Pull full CommcareHQ source
      git:
        repo: "{{ commcarehq_repository }}"
        dest: "{{ code_source }}"
        version: "{{ commcarehq_version }}"
        recursive: yes
        accept_hostkey: yes
        update: yes
      become: true
      tags:
        - git
        - slow

    - name: Link source to code_home
      become: true
      file:
        state: link
        src: "{{ code_source }}"
        dest: "{{ code_home }}"
        owner: "{{ cchq_user }}"
        group: "{{ cchq_user }}"

    - name: install pip requirements
      become: true
      with_items: "{{ commcarehq_requirements }}"
      pip:
        requirements: "{{ code_home }}/requirements/{{ item }}"
        virtualenv: "{{ virtualenv_source }}"
        chdir: "{{ code_home }}"
      tags:
        - slow
      when: not testing|default(False)

    - name: chown clone
      become: true
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ cchq_user }}"
        group: "{{ cchq_user }}"
        recurse: yes
      with_items:
        - "{{ code_source }}"
        - "{{ virtualenv_source }}"

  when: not gitdir.stat.exists

- name: Upgrade python packages
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_home }}"
  with_items:
    - six
    - pip
    - setuptools

- name: copy localsettings
  become: true
  template:
    src: localsettings.py.j2
    dest: "{{ code_home }}/localsettings.py"
  tags:
    - localsettings
    - hq-localsettings

- name: chown localsettings
  become: true
  file:
    path: "{{ code_home }}/localsettings.py"
    state: file
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
  tags:
    - localsettings
    - hq-localsettings

- include_vars: "../../../../environments/{{ deploy_env }}/app-processes.yml"
  tags:
    - services

- name: define pillowtop services
  become: cchq
  hosts: pillowtop
  template:
    src: supervisor_pillowtop.conf.j2
    dest: "{{ services_home }}/{{ deploy_env }}_supervisor_pillowtop.conf"
  tags:
    - services

- name: define form feed service
  become: cchq
  hosts: pillowtop
  template:
    src: supervisor_form_feed.conf.j2
    dest: "{{ services_home }}/{{ deploy_env }}_supervisor_form_feed.conf"
  tags:
    - services

- name: define reminder queue services
  become: cchq
  hosts: celery
  template:
    src: "{{ item }}"
    dest: "{{ services_home }}/{{ deploy_env }}_{{ item }}"
  when: 'reminder_queue' in celery_processes.get(ansible_host)
  items:
    - supervisor_reminder_queue.conf
    - supervisor_queue_schedule_instances.conf
    - supervisor_handle_survey_actions.conf
  tags:
    - services

- name: define submission reprocessing queue services
  become: cchq
  hosts: celery
  template:
    src: "supervisor_submission_reprocessing_queue.conf"
    dest: "{{ services_home }}/{{ deploy_env }}_supervisor_submission_reprocessing_queue.conf"
  when: 'submission_reprocessing_queue' in celery_processes.get(ansible_host)
  tags:
    - services

- name: define pillow retry queue services
  become: cchq
  hosts: celery
  template:
    src: "supervisor_pillow_retry_queue.conf"
    dest: "{{ services_home }}/{{ deploy_env }}_supervisor_pillow_retry_queue.conf"
  when: 'pillow_retry_queue' in celery_processes.get(ansible_host)
  tags:
    - services

- name: define websockets services
  become: cchq
  hosts: proxy
  template:
    src: "supervisor_websockets.conf"
    dest: "{{ services_home }}/{{ deploy_env }}_supervisor_websockets.conf"
  tags:
    - services
