- include_vars: "../../../../environments/{{ deploy_env }}/app-processes.yml"
  tags:
    - services

- name: define pillowtop services
  become: cchq
  hosts: pillowtop
  template:
    src: "../templates/supervisor_pillowtop.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_pillowtop.conf"
  tags:
    - services

- name: define form feed service
  become: cchq
  hosts: pillowtop
  template:
    src: "../templates/supervisor_form_feed.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_form_feed.conf"
  tags:
    - services
