- include_vars: "../../../../environments/{{ deploy_env }}/app-processes.yml"
  tags:
    - services

- name: define errand boy services
  become: cchq
  template:
    src: "../templates/supervisor_errand_boy.conf"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_errand_boy.conf"
  tags:
    - services
