- name: define formplayer spring services
  become: cchq
  template:
    src: "../templates/supervisor_formplayer_spring.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_formplayer_spring.conf"
  tags:
    - services
  register: formplayer_files

- name: remove old formplayer spring services
  become: yes
  become_user: cchq
  file:
    state: absent
    path: "{{ legacy_service_home }}/supervisor/{{ deploy_env }}_supervisor_formplayer_spring.conf"
  tags:
    - services

- set_fact:
    formplayer_supervisor_files: "{{ formplayer_files.get('results', [])"

- set_fact:
    formplayer_managed_files: "{{ formplayer_supervisor_files|selectattr('dest', 'string')|map(attribute='dest')|list }"
