- name: register git repo
  stat: path="{{ dest }}/.git"
  register: gitdir

- block:
  - name: Pull source repo
    git:
      repo: "{{ url }}"
      dest: "{{ dest }}"
      version: "{{ version }}"
      recursive: yes
      accept_hostkey: yes
      update: yes
    become_user: "{{ cchq_user }}"
    tags:
      - git
      - slow

  - name: install pip requirements
    pip:
      requirements: "{{ dest }}/{{ requirements_path }}"
      virtualenv: "{{ py3_virtualenv_source }}"
      virtualenv_python: "python3.6"
      chdir: "{{ code_source }}"
    when: not testing|default(False)
    tags:
      - slow
      - py3

  when: (CCHQ_IS_FRESH_INSTALL is defined and CCHQ_IS_FRESH_INSTALL) or not gitdir.stat.exists
  become: true
