- name: define pillowtop services
  become: yes
  template:
    src: "../templates/supervisor_pillowtop.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_pillowtop.conf"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  with_items:
    - env_vars:
        TMPDIR: '{{ encrypted_tmp }}'
        READ_FROM_PLPROXY_STANDBYS: 1
        prometheus_multiproc_dir: "{% if prometheus_monitoring_enabled|default(False) %}{{ cchq_home}}/www/{{ deploy_env }}/metrics{% endif %}"
  tags:
    - services
  register: pillowtop_conf_file

- set_fact:
    pillowtop_supervisor_files: "{{ [pillowtop_conf_file] }}"
  tags:
    - services

- set_fact:
    pillowtop_managed_files: "{{ pillowtop_supervisor_files|selectattr('dest', 'string')|map(attribute='dest')|list + pillowtop_supervisor_files|selectattr('path', 'string')|map(attribute='path')|select|list }}"
  tags:
    - services
