- name: Creates Prometheus Metrics directory
  become: yes
  file: 
    path: "{{ metrics_home }}"
    state: directory
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
  tags: services

- name: define prometheus service
  become: yes
  template:
    src: "../templates/supervisor_prometheus.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_prometheus.conf"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  tags:
    - services
  when: prometheus_monitoring_enabled|default(False)
  register: prometheus_conf_file

- name: Add django_bash_runner
  become: yes
  template:
    src: "../templates/django_bash_runner.sh.j2"
    dest: "{{ django_bash_runner_path }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  when: prometheus_monitoring_enabled|default(False)
  tags:
    - services
  register: django_bash_runner_files

- set_fact:
    prometheus_supervisor_files: "{{ [prometheus_conf_file] }}"
  tags:
    - services

- set_fact:
    prometheus_managed_files: "{{ prometheus_supervisor_files|selectattr('dest', 'string')|map(attribute='dest')|list + prometheus_supervisor_files|selectattr('path', 'string')|map(attribute='path')|select|list }}"
  tags:
    - services
