---
# roles/webworker/handlers/main.yml

- name: restart webworker app
  supervisorctl: name={{app_name}} state=restarted

- name: stop webworker app
  supervisorctl: name={{app_name}} state=stopped

- name: start webworker app
  supervisorctl: name={{app_name}} state started

