- include_vars: ../../postgresql/defaults/main.yml

- name: Install pgBackRest and requirements
  apt: name={{item}} state=installed
  with_items:
     - pgbackrest

- name: Editing postgresql.conf file
  become: True
  blockinfile:
    dest: "{{ postgresql_config_home }}/postgresql.conf"
    block: |
      archive_command = 'pgbackrest --stanza=backup archive-push %p'
      archive_mode = on
      max_wal_senders = 3
      wal_level = hot_standby
  notify: Restart postgres
  when: not is_pg_standby
  
- name: Creating pgbackrest.conf file
  become: True
  template:
    src=pgbackrest.conf.j2
    dest=/etc/pgbackrest.conf
    owner=postgres
    group=postgres
    mode=640

- name: Creating postgres stanza
  become: True
  become_user: postgres
  vars:
    ansible_ssh_pipelining: True
  shell: pgbackrest --stanza=backup --log-level-console=info stanza-create
  when: is_pg_standby

- name: Create Daily Cron job
  sudo: yes
  cron:
    name: "Backup postgres daily (incremental)"
    job: "/usr/bin/pgbackrest --type=incr --stanza=backup backup"
    minute: 0
    hour: "{{ nadir_hour|default(0) }}"
    weekday: "1,2,3,4,5,6"
    user: postgres
    cron_file: backup_postgres
  when: backup_postgres and is_pg_standby

- name: Create Weekly Cron job
  sudo: yes
  cron:
    name: "Backup postgres weekly (full backup)"
    job: "/usr/bin/pgbackrest --type=full --stanza=backup backup"
    minute: 0
    hour: "{{ nadir_hour|default(0) }}"
    weekday: 0
    user: postgres
    cron_file: backup_postgres
  when: backup_postgres and is_pg_standby
