---
# Send anything from http://commcarehq.org -> http://www.commcarehq.org
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_commcare_static_redirect"
   listen: "80"
   server_name: "{{ WWW_SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    return: "301 http://{{ SITE_HOST }}$request_uri"
