---
nginx_sites:
- server:
   balancers:
    - name: "{{ deploy_env }}_commcare"
      hosts: webworkers
      port: "{{ django_port }}"
    - name: "{{ deploy_env }}_formplayer"
      hosts: formplayer
      port: "{{ formplayer_port }}"
      method: "hash $cookie_sessionid consistent"
   proxy_cache_path:
    - name: "prelogin_cache"
      path: "{{ www_home }}/prelogin_cache"
      max_size: "3g"
      inactive_time: "24h"
   file_name: "{{ deploy_env }}_commcare"
   listen: "443 ssl{{ ' default_server' if deploy_env == primary_ssl_env else '' }}"
   root: "/var/www/html"
   server_name: "{{ SITE_HOST }}"
   client_max_body_size: 500m
   proxy_set_headers:
   - "Host $host"
   - "X-Forwarded-For $remote_addr"
   add_header: "X-Frame-Options SAMEORIGIN"
   access_log: "{{ log_home }}/{{ deploy_env }}-timing.log timing"
   locations:
    - name: "~* ^(\/lang\/(\w+))?/(home|impact|pricing|services|software|solutions|askdemo)/$"
      balancer: "{{ deploy_env }}_commcare"
      proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 900s
      proxy_cache: prelogin_cache
      proxy_cache_use_stale: "error timeout updating http_500 http_502 http_503 http_504"
      proxy_cache_methods: GET
      add_header: X-Cache-Status $upstream_cache_status
    - name: /
      balancer: "{{ deploy_env }}_commcare"
      proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 900s
    - name: "/static"
      alias: "{{ nginx_static_home }}"
      add_header: "Access-Control-Allow-Origin *"
      expires: "1M"
      try_files: "$uri $uri/index.html $uri/ =404"
    - name: "/{{ transfer_payload_dir_name }}"
      alias: "{{ shared_mount_dir if shared_drive_enabled else shared_data_dir }}/{{ transfer_payload_dir_name }}"
      is_internal: True
    - name: /errors
      alias: "{{ errors_home }}/pages"
    - name: /ws
      proxy_pass: "http://unix:{{ www_home }}/web.socket"
      proxy_http_version: "1.1"
      proxy_set_headers:
      - "Upgrade $http_upgrade"
      - "Connection \"upgrade\""
    - name: /formplayer
      balancer: "{{ deploy_env }}_formplayer/"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 900s
   extra_locations: "{{ site_locations|default([]) }}"
