---
server:
 file_name: "{{ deploy_env }}_commcare_static"
 listen: "80"
 server_name: "{{ WWW_SITE_HOST }}"
 client_max_body_size: 100m
 use_balancer: True
 proxy_set_header: "Host $http_host"
 location1:
  name: /
  return: "301 https://$server_name$request_uri"
 location2:
  name: "~* /(?:home|users|support|plans|images|pdfs|style|js|tour|div2|docs|fr|poc|es)/"
  alias: "{{ static_site_path }}/$1"
  try_files: "$uri $uri/index.html $uri/ =404"
