---
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_commcare"
   listen: "443 ssl"
   server_name: "{{ SITE_HOST }}"
   client_max_body_size: 100m
   use_balancer: True
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    use_balancer: True
    proxy_redirect: "http://staging.commcarehq.org https://staging.commcarehq.org"
   location2:
    name: "~* /static"
    alias: "{{ nginx_static_home }}"
    try_files: "$uri $uri/index.html $uri/ =404"
