---
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_commcare"
   listen: "443 ssl"
   server_name: "{{ SITE_HOST }}"
   client_max_body_size: 100m
   use_balancer: True
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    # The /dev/null is a hack because try files require more than one argument,
    # might make sense to remove the @proxy_to_app and just use proxy_pass
    try_files: "/dev/null @proxy_to_app"
    proxy_set_header: "X-Real-IP $remote_addr"
    proxy_set_header: "X-Forwarded-For $proxy_add_x_forwarded_for"
    proxy_set_header: "X-Forwarded-Proto $scheme"
    proxy_redirect: "http://staging.commcarehq.org https://staging.commcarehq.org"
   location2:
    name: "@proxy_to_app"
    use_balancer: True
   location3:
    name: "~* /static"
    alias: "{{ nginx_static_home }}"
    try_files: "$uri $uri/index.html $uri/ =404"
