---
nginx_sites:
- server:
   file_name: commtrack
   listen: "8443 ssl"
   server_name: "{{ COMMTRACK_SITE_HOST }}"
   client_max_body_size: 100m
   use_balancer: True
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    use_balancer: True
    proxy_redirect: "http://{{ COMMTRACK_SITE_HOST }} https://{{ COMMTRACK_SITE_HOST }}"
   location2:
    name: /static
    alias: "{{ nginx_static_home }}"
