---
nginx_sites:
- server:
   file_name: motech
   listen: "443 ssl"
   # Move these to a localsetting?
   server_name: endos-motech.commcarehq.org
   proxy_set_headers:
   - "Host $http_host"
   - "X-Forwarded-For $remote_addr"
   - "X-Forwarded-Proto $scheme"
   - "X-Forwarded-Host $host:443"
   location1:
    name: /
    proxy_pass: http://motech.internal.commcarehq.org:8080/motech-platform-server/
    proxy_redirect: "http://endos-motech.commcarehq.org/motech-platform-server/ https://endos-motech.commcarehq.org/"
   location2:
    name: /errors
    alias: "{{ errors_home }}/pages"
