---
nginx_sites:
- server:
   file_name: motech1
   listen: "443 ssl"
   # Move these to a localsetting?
   server_name: test-endos-motech.commcarehq.org
   proxy_set_headers:
   - "Host $http_host"
   - "X-Forwarded-For $remote_addr"
   - "X-Forwarded-Proto $scheme"
   - "X-Forwarded-Host $host:443"
   error_page: "502 503 /errors/50x.html"
   location1:
    name: /
    proxy_pass: http://motech1.internal.commcarehq.org:8080
   location2:
    name: /errors
    alias: "{{ errors_home }}/pages"
