---
nginx_sites:
- server:
   file_name: sentry
   listen: "443 ssl"
   # Move these to a localsetting?
   server_name: sentry.commcarehq.org
   location1:
    name: /
    proxy_pass: http://logs.internal.dimagi.com:9000
