---
# Send anything from http -> https
nginx_sites:
- server:
   file_name: "tableau_http"
   listen: "80"
   server_name: "tableau.commcarehq.org"
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    return: "301 https://$server_name"
