---
nginx_sites:
- server:
   file_name: wiki
   listen: "443 ssl"
   server_name: "wiki.commcarehq.org help.commcarehq.org"
   location1:
    name: /
    proxy_pass: http://confluence.dimagi.com
   location2:
    name: "= /"
    return: "302 https://$server_name/display/commcarepublic/Home"
