---

- name: Install NFS packages
  sudo: yes
  when: shared_drive_enabled
  apt: name={{ item }} state=present
  with_items:
    - nfs-kernel-server
    - portmap
  tags:
    - nfs

- name: ensure nfs service is running
  when: shared_drive_enabled
  service:
    name: nfs-kernel-server
    state: started
  tags:
    - nfs

- name: Create group with same GID
  sudo: yes
  when: shared_drive_enabled
  group:
    name: "{{ shared_dir_groupname }}"
    state: present
    gid: "{{ shared_dir_gid }}"
  tags:
    - nfs

- name: Add cchq to nfs group
  when: shared_drive_enabled
  user:
    name: "{{ cchq_user }}"
    groups: "{{ shared_dir_groupname }}"
    append: yes
  tags:
    - nfs
