---

- name: Create shared mount dir
  sudo: yes
  when: shared_drive_enabled
  file:
    path: "{{ shared_mount_dir }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: 0775
    state: directory
  tags:
    - nfs

- name: Mount directory in /etc/fstab
  sudo: yes
  when: shared_drive_enabled
  mount:
    name: "{{ shared_mount_dir }}"
    src: "{{ groups.shared_dir_host[0] }}:{{ shared_data_dir }}"
    fstype: nfs
    state: mounted
  tags:
    - nfs

- name: Create blob DB mount point
  sudo: yes
  dependencies:
    - role: ecryptfs
  when: shared_drive_enabled
  file: path={{ shared_mount_dir }}/blobdb owner=root group=root mode=0755 state=directory
  tags:
    - ecryptfs
    - ecryptfs-blobdb

- name: Mount blob DB NFS volume
  sudo: yes
  dependencies:
    - role: ecryptfs
  when: shared_drive_enabled
  shell: "mount -t nfs {{ groups.shared_dir_host[0] }}:/opt/data/blobdb {{ shared_mount_dir }}/blobdb"
  tags:
    - ecryptfs
    - ecryptfs-blobdb
