---

- name: Create shared data dir
  sudo: yes
  file:
    path: "{{ shared_data_dir }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  tags:
    - nfs

- name: Add shared dir to exports
  sudo: yes
  lineinfile:
    dest: /etc/exports
    line: "{{ shared_data_dir }} {{ item }}(rw,sync,all_squash,no_subtree_check,anongid={{ shared_dir_gid }})"
    regexp: "^{{ shared_data_dir }} {{ item }}"
    state: present
  with_flattened:
    - groups.webworkers
    - groups.proxy
  tags:
    - nfs

- name: Export directories
  sudo: yes
  command: "exportfs -a"
  tags:
    - nfs

- name: create shared directories
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - "{{ restore_payload_dir }}"
    - "{{ transer_payload_dir }}"
  tags:
    - shared_files

- name: Create purging cron jobs
  sudo: yes
  cron:
    name: "{{ item.name }}"
    special_time: daily
    job: "find {{ item.dir }} -type f -maxdepth 1 -mtime +4 -delete"
    user: root
    cron_file: purge_cache_files
  with_items:
    - {name: 'Purge old restore files', dir: "{{ restore_payload_dir }}"}
    - {name: 'Purge old transfer files', dir: "{{ transer_payload_dir }}"}
  tags:
    - shared_files

