---

- name: Add shared dir to exports
  sudo: yes
  lineinfile:
    dest: /etc/exports
    line: "{{ shared_data_dir }} {{ item }}(rw,sync,all_squash,no_subtree_check,anongid={{ shared_dir_gid }})"
    regexp: "^{{ shared_data_dir }} {{ item }}"
    state: present
  with_flattened:
    - groups.webworkers
    - groups.proxy
    - groups.celery
    - groups.pillowtop
    - groups.shared_dir_host
  tags:
    - nfs

- name: Export directories
  sudo: yes
  command: "exportfs -a"
  tags:
    - nfs
