---
- set_fact:
    first_master_ip: "{{ hostvars[hostvars.keys()[0]].ansible_default_ipv4.address }}"

- name: Add cluster config
  lineinfile:
    dest: /etc/redis/{{ redis_port }}.conf
    line: '{{ item.key }} {{ item.value }}'
  with_dict: "{{ cluster_config }}"

- name: start the redis service
  service: name="{{ redis_service_name }}" state=started enabled=yes
  tags: after-reboot

- name: Join nodes to cluster
  shell: "redis-cli cluster meet {{ first_master_ip }} 6379"
  when: ansible_eth0["ipv4"]["address"] != first_master_ip
