---
# roles/webworker/tasks/main.yml

- name: copy webworker source
  git: repo={{repository}} dest="/home/{{cchq_user}}/www/{{deploy_env}}/code_root/" version={{cchq_version}} accept_hostkey=yes
  notify:
    - install pip requirements
    - copy roledefs file
    - copy localsettings
    - restart webworker app
