---
# roles/webworker/tasks/main.yml

- name: setup django
  git: repo={{cchq_repository}} dest={{code_home}} version={{cchq_version}} accept_hostkey=yes depth=1
  sudo: yes
  sudo_user: "{{cchq_user}}"
  notify:
    - install pip requirements

- name: copy localsettings
  sudo: yes
  sudo_user: "{{cchq_user}}"
  template:
    src: localsettings.py.j2
    dest: "{{code_home}}/localsettings.py"
  notify: restart webworker app
