- name: create required directories
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ errors_home }}"

- name: pull errors repository
  git:
    repo={{ commcarehq_errors_repository }} dest={{ errors_home }} version=master recursive=yes accept_hostkey=yes depth=1
  sudo_user: "{{ cchq_user }}"
  tags:
    - git
