---
- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install nginx
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: nginx_ubuntu_pkg
  when: nginx_install == True

- name: Create nginx http user
  sudo: yes
  user: name={{ nginx_user }} createhome=no password=no state=present groups="{{ cchq_user }}"
  when: nginx_install == True

- name: Create nginx logfile home
  sudo: yes
  file: path={{ log_home }} owner={{ cchq_user }} group={{ cchq_user }} mode=0770 state=directory
  when: nginx_install == True

- name: Create static files home
  sudo: yes
  file: path={{ nginx_static_home }} owner={{ cchq_user }} group={{ cchq_user }} mode=0755 state=directory
  when: nginx_install == True

- name: Copy the nginx configuration file
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Copy the nginx default configuration file
  sudo: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Copy the nginx default site configuration file
  sudo: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Create the link for site enabled specific configurations
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: Create directories for certificates
  file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - "{{ ssl_certs_dir }}"
    - "{{ ssl_keys_dir }}"


- name: Copy cchq SSL cert
  copy:
    src: "{{ nginx_combined_cert_file }}"
    dest: "{{ ssl_certs_dir }}/{{ nginx_ssl_cert }}"
    mode: 0400
    owner: root
    group: root
  when: not fake_ssl_cert

- name: Copy cchq SSL Key
  copy:
    src: "{{ apache2_key_file }}"
    dest: "{{ ssl_keys_dir }}/{{ nginx_ssl_key }}"
    mode: 0400
    owner: root
    group: root
  when: not fake_ssl_cert

- name: Copy commtrack SSL cert
  copy:
    src: "{{ commtrack_nginx_combined_cert_file }}"
    dest: "{{ ssl_certs_dir }}/{{ commtrack_nginx_ssl_cert }}"
    mode: 0400
    owner: root
    group: root
  when: not fake_ssl_cert and commtrack_nginx_combined_cert_file is defined

- name: Copy commtrack SSL Key
  copy:
    src: "{{ commtrack_apache2_key_file }}"
    dest: "{{ ssl_keys_dir }}/{{ commtrack_nginx_ssl_key }}"
    mode: 0400
    owner: root
    group: root
  when: not fake_ssl_cert and commtrack_apache2_key_file is defined
