---
- name: CitusDB
  hosts: citusdb
  become: true
  roles:
    - {role: citusdb, tags: 'citusdb'}

- name: pgbouncer
  hosts: citusdb_cordinator
  become: true
  roles:
    - {role: pgbouncer, tags: 'citusdb_cordinator'}


# Disables transparent huge pages (THP)
- name: Disable THP
  become: true
  hosts:
    - citusdb
  tags: 'kernel_tuning'
  roles:
    - role: thp
