---
- name: Sentry Machine Setup
  hosts: sentry
  become: true
  environment:
    JMX_PORT: 9999
  vars:
    - postgresql_version: 11
    - redis_bind: 127.0.0.1
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}
    - {role: postgresql, tags: 'postgresql_sentry'}
    - {role: DavidWittman.redis, tags: 'redis_sentry'}
    - {role: zookeeper, tags: 'zookeeper_sentry'}
    - {role: kafka, tags: 'kafka_sentry'}

- name: Install and Configure Sentry
  hosts: sentry
  become: true
  vars:
    - sentry_dbuser: "{{ secrets.POSTGRES_USERS.commcare.username }}"
    - sentry_dbpassword: "{{ secrets.POSTGRES_USERS.commcare.password }}"
    - sentry_database: sentrydb
    - sentry_system_secret_key: "{{ secrets.SENTRY_SYSTEM_SECRET_KEY }}"
    - clickhouse_data_dir: "{{ encrypted_root }}/clickhouse"
  roles:
    - {role: sentry, tags: 'sentry'}
