- name: "Create host group aliases"
  hosts: all
  tasks:
    - name: Create all_commcarehq group alias
      add_host:
        hostname: "{{ item }}"
        groups: all_commcarehq
      with_items: "{{ groups['all'] }}"
      when: "item not in groups['openvpn']|default([])"
  tags:
    - always
