- name: "Create host group aliases"
  hosts: all
  tasks:
    - name: Create all_commcarehq group alias
      group_by: key=all_commcarehq
      when: "'openvpn' not in group_names"
      changed_when: no
    - name: Create commcarehq group alias
      group_by: key=commcarehq
      when: |
        ('webworkers' in group_names) or
        ('formplayer' in group_names) or
        ('celery' in group_names) or
        ('proxy' in group_names) or
        ('pillowtop' in group_names) or
        ('couchdb2_proxy' in group_names) or
        ('airflow' in group_names) or
        ('django_manage' in group_names)
      changed_when: no
  tags:
    - always

