- name: Barman
  hosts: pg_barman
  become: true
  roles:
    - {role: barman}
  tags:
    - barman_deploy

- name: Setup auth for postgres
  hosts:
    - pg_barman_source
  vars:
    - userFrom: postgres
    - hostTo: "{{ groups['pg_barman'].0 }}"
    - userTo: barman
    - state: 'present'
  tasks:
    - import_tasks: roles/setup_auth_keys.yml
      when: groups['pg_barman_source']|length
  tags:
    - pg_barman

- name: Setup auth for barman
  hosts:
    - pg_barman
  vars:
    - userFrom: barman
    - hostTo: "{{ groups['pg_barman_source'] }}"
    - userTo: postgres
    - state: 'present'
  tasks:
    - import_tasks: roles/setup_auth_keys.yml
      when: groups['pg_barman']|length
  tags:
    - pg_barman
