- name: Barman
  hosts: pg_barman
  become: true
  roles:
    - {role: barman}

- name: Setup auth for postgres
  hosts:
    - barman_source
  vars:
    - userFrom: postgres
    - hostTo: "{{ groups['pg_barman'].0 }}"
    - userTo: barman
    - state: 'present'
  tasks:
    - import_tasks: roles/setup_auth_keys.yml
      when: groups['barman_source']|length
  tags:
    - pg_barman
