- name: Cleanup shared dir clients
  hosts: webworkers:proxy:celery:pillowtop:shared_dir_host
  sudo: yes
  vars_files:
    - shared_dir/vars/main.yml
  tasks:
    - include: shared_dir/tasks/cleanup_client.yml

- name: Cleanup shared dir host
  hosts: shared_dir_host
  sudo: yes
  vars_files:
    - shared_dir/vars/main.yml
  tasks:
    - include: shared_dir/tasks/cleanup_host.yml
