---
# deploy-staging-db.yml
- name: Databases
  hosts: db
  sudo: yes
  serial: 1

  roles:
    - common
    - postgresql
    - couchdb
    - { role: bennojoy.memcached }
    - { role: bennojoy.redis }
