---
- name: Common Database Machine Setup
  hosts:
    - postgresql
    - couchdb
    - redis
    - elasticsearch
    - rabbitmq
  sudo: yes
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}

- name: Postgresql
  hosts: postgresql
  sudo: yes
  roles:
    - {role: postgresql, tags: 'postgresql'}

- name: Couchdb
  hosts: couchdb
  sudo: yes
  roles:
    - {role: couchdb, tags: 'couchdb'}

- name: Redis
  hosts: redis
  sudo: yes
  roles:
    - {role: redis, tags: 'redis'}

- name: Elasticsearch
  hosts: elasticsearch
  sudo: yes
  roles:
    - {role: elasticsearch, tags: 'elasticsearch'}

- name: Redis Monitoring
  hosts: redis
  sudo: yes
  roles:
    - redis_monitoring

- name: RabbitMQ
  hosts: rabbitmq
  sudo: yes
  roles:
    - rabbitmq

- name: Newrelic Plugin Agent for DB
  hosts:
    - postgresql
    - redis
    - rabbitmq
  tasks:
    - include: roles/newrelic/tasks/plugin-agent.yml
      when: run_newrelic_plugin_agent
  tags:
    - newrelic-plugin-agent

- name: Postgres log rolling configurations
  hosts: postgresql
  vars_files:
    - roles/postgresql/defaults/main.yml
  roles:
    - role: ansible-logrotate
      logrotate_scripts:
        - name: "postgresql_{{ deploy_env }}"
          path: "{{ postgresql_dir_path }}/{{ postgresql_version }}/main/pg_log/*"
          options:
            - daily
            - rotate 30
            - missingok
            - compress
            - delaycompress
            - notifempty
