- name: Common
  hosts: all
  sudo: yes
  roles:
    - common

- name: ufw (firewall)
  hosts: '!proxy'
  sudo: yes
  roles:
    - {role: ufw, tags: ufw, when: ufw_private_interface is defined}

- name: ufw (proxy firewall)
  hosts: 'proxy'
  sudo: yes
  tasks:
    - include: roles/ufw/tasks/proxy_ufw.yml tags=ufw-proxy
      when: ufw_private_interface is defined or is_monolith

- name: Datadog agent
  hosts: all
  sudo: yes
  roles:
    - {role: datadog, tags: datadog, when: DATADOG_ENABLED}
