---
# deploy-staging-db.yml
- name: Databases
  hosts: db
  sudo: yes
  vars_files:
    - "vars/{{ deploy_env }}.yml"
  roles:
    - ecryptfs
    - postgresql
    - couchdb
    - bennojoy.memcached
    - bennojoy.redis
    - elasticsearch
    - monitoring
