- name: Common
  hosts: all
  become: true
  roles:
    - common

- name: ufw (firewall)
  hosts: '!proxy:!cas_proxy:!enikshay_proxy:!pna_proxy:!couchdb2_proxy'
  become: true
  roles:
    - {role: ufw, tags: ufw, when: ufw_private_interface is defined}

- name: ufw (proxy firewall)
  hosts: 'proxy:cas_proxy:enikshay_proxy:pna_proxy:couchdb2_proxy'
  become: true
  tasks:
    - include: roles/ufw/tasks/proxy_ufw.yml tags=ufw-proxy
      when: ufw_private_interface is defined or is_monolith|bool

- name: Datadog agent
  hosts: all
  become: true
  roles:
    - {role: datadog, tags: datadog, when: DATADOG_ENABLED}

- name: Configure swap
  hosts: all
  roles:
    - {role: swap}

- name: Configure monit
  hosts: all
  roles:
    - {role: monit, tags: monit}

- name: Configure static routes
  hosts: all
  tasks:
  - name: Adds static routes
    shell: 'if [ `ip route show {{ item.prefix }} | wc -l` -eq "0" ];  then route add -net {{ item.prefix }} gw {{ item.gateway }}; else echo "already_exists"; fi'
    with_items: "{{ static_routes }}"
    become: True
    register: route_show
    changed_when: '"already_exists" not in route_show.stdout'
    tags: static_routes
