---
- name: Common Database Machine Setup
  hosts:
    - postgresql
    - couchdb
    - redis
    - elasticsearch
    - rabbitmq
    - zookeeper
  sudo: yes
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}
    - {role: backups, tags: 'backups'}

- name: Postgresql
  hosts: postgresql
  sudo: yes
  roles:
    - {role: postgresql, tags: 'postgresql'}

- name: Couchdb
  hosts: couchdb
  sudo: yes
  roles:
    - {role: couchdb, tags: 'couchdb'}

- name: Redis
  hosts: redis
  sudo: yes
  roles:
    - {role: redis, tags: 'redis'}

- name: Elasticsearch
  hosts: elasticsearch
  sudo: yes
  roles:
    - {role: elasticsearch, tags: 'elasticsearch'}

- name: Redis Monitoring
  hosts: redis
  sudo: yes
  roles:
    - redis_monitoring

- name: RabbitMQ
  hosts: rabbitmq
  sudo: yes
  roles:
    - rabbitmq

- name: Zookeeper
  hosts: zookeeper
  sudo: yes
  roles:
    - {role: zookeeper, tags: 'zookeeper'}

- name: Kafka
  hosts: kafka
  sudo: yes
  roles:
    - {role: kafka, tags: 'kafka'}

- name: Newrelic Plugin Agent for DB
  hosts:
    - postgresql
    - redis
    - rabbitmq
  tasks:
    - include: roles/newrelic/tasks/plugin-agent.yml
      when: run_newrelic_plugin_agent
  tags:
    - newrelic-plugin-agent

- name: Load admin keys from Riak CS conf
  sudo: True
  hosts: riakcs
  vars_files:
    - roles/riakcs/defaults/main.yml
  tasks:
    - include: roles/riakcs/tasks/get_admin_keys.yml
      # HACK use `when` because can't figure out how to use `hosts` to run on just riakcs_control
      when: inventory_hostname == riakcs_control
      tags:
        - riakcs

- name: Stanchion
  sudo: True
  hosts:
    - stanchion
  roles:
    - { role: stanchion, tags: [stanchion, riakcs] }

- name: Riak Cluster
  sudo: True
  hosts:
    - riakcs
  roles:
    - { role: riakcs, tags: riakcs }

- name: Sync Stanchion conf keys after creating Riak CS admin user
  sudo: True
  hosts:
    - stanchion
  vars_files:
    - roles/stanchion/vars/main.yml
  tasks:
    - include: roles/riakcs/tasks/set_admin_keys.yml
      vars:
        path: "{{ stanchion_conf }}"
        service: stanchion
      tags:
        - riakcs
  handlers:
    - include: roles/stanchion/handlers/main.yml

- name: Check for Riak CS admin user/key creation failure
  # fail after all other tasks have been done so keys are synced and a
  # subsequent run should be able to reset them
  hosts: riakcs
  tasks:
    - name: Admin user creation failed
      fail:
        msg: Unable to create admin user
             {{ riak_create_user_result | to_nice_json }}
      when: "inventory_hostname == riakcs_control and
             riak_create_user_result is defined and (
              'key_id' not in riakcs_admin_user or
              'key_secret' not in riakcs_admin_user)"
      tags:
        - riakcs

# Note other machines also have java installed, but are initiated through the meta task
- name: Java
  sudo: True
  hosts:
    - celery
  roles:
    - {role: java, tags: java}
