- name: Bootstrap Control
  hosts: localhost
  gather_facts: no
  become: true
  roles:
    - {role: users, tags: users}
    - {role: ssh, tags: ssh}
    - role: edit
    - {role: ksplice, tags: ksplice}
    - {role: ansible-control, tags: ansible-control}
