- name: zabbix server deploy
  hosts: zabbix
  sudo: yes
  roles:
    - {role: jonatasbaldin.zabbix3server, tags: 'zabbix_server'}

- name: zabbix agent deploy
  hosts: all
  sudo: yes
  roles:
    - {role: jonatasbaldin.zabbix3agent, tags: 'zabbix_agent'}
    - {role: zabbix_integrations, tags: 'zabbix_integrations'}
