---
- src: git+https://github.com/andrewrothstein/ansible-couchdb-cluster.git
  version: b7253a9f980a0a9a86f68881047775dff8aa554d
  name: emord.ansible-couchdb-cluster
- src: git+https://github.com/debops-contrib/ansible-etckeeper.git
  version: 29c721de3df965ff355cbed242db813f70b811a2
  name: debops-contrib.etckeeper
- src: git+https://github.com/ANXS/tmpreaper.git
  version: 46f8e0b8b8f5732eecc68b08b5e0c392c418e3f3
  name: tmpreaper
