---
# Runs an individual ansible role
# Usage:
#   ansible-playbook ./run_role.yml -i "hostname," -e role=my_awesome_role
#
- hosts: all
  gather_facts: True
  vars_files:
    - "vars/{{ deploy_env }}.yml"
  roles:
    - "{{ role }}"
