---
# roles/postgresql/tasks/main.yml

- name: Install PostgreSQL & dependencies
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  when:
    pg_install == True

- name: generate en_US.UTF-8 locale
  locale_gen: name='en_US.UTF-8' state=present
  when:
    pg_install == True

- name: PostgreSQL app configuration
  sudo_user: postgres
  template: src=postgresql.conf.j2 dest={{ postgresql_config_home }}/postgresql.conf
  when:
    pg_install == True

- name: PostgreSQL access configuration
  sudo_user: postgres
  template: src=pg_hba.conf.j2 dest={{ postgresql_config_home }}/pg_hba.conf

- name: start postgresql
  service: name=postgresql state=started

- name: Create PostgreSQL databases
  sudo_user: postgres
  postgresql_db: name={{ item }} state=present
  with_items: postgresql_dbs
  when:
    pg_install == True

- name: Create PostgreSQL users
  sudo_user: postgres
  postgresql_user:
    name: "{{ localsettings.PG_DATABASE_USER }}"
    password: "{{ localsettings.PG_DATABASE_PASSWORD }}"
    role_attr_flags: CREATEDB
    state: present
  when:
    pg_install == True
