- name: Copy Redis restart script
  sudo: yes
  template:
    src: "redis-restart.sh.j2"
    dest: "/usr/local/sbin/redis-restart.sh"
    group: root
    owner: root
    mode: 0700
    backup: yes

- name: Create Cron job
  sudo: yes
  cron:
    name: "Reboot Redis"
    job: "/usr/local/sbin/redis-restart.sh > /dev/null"
    user: root
    cron_file: ../crontab
