- name: Copy Redis restart script
  sudo: yes
  file:
    dest: "/usr/local/sbin/redis-restart.sh"
    state: absent

- name: Create Cron job
  sudo: yes
  cron:
    name: "Reboot Redis"
    job: "/usr/local/sbin/redis-restart.sh > /dev/null"
    user: root
    cron_file: ../crontab
    state: absent
