---
# Send anything from http -> https
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_reach_commcare_static"
   listen: "80"
   server_name: "{{ REACH_SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_headers:
   - "Host $host"
   - "X-Forwarded-Protocol  $scheme"
   locations:
     - name: /
       return: "301 https://$server_name$request_uri"
