---
- name: Install Vim
  sudo: yes
  apt: name=vim state=present update_cache=yes cache_valid_time=3600

- name: Install Emacs
  sudo: yes
  apt: name=emacs23 state=present update_cache=yes cache_valid_time=3600

- name: Include vimrc
  sudo: yes
  copy:
    src: vimrc
    dest: /etc/vimrc
    owner: root
    group: root
    mode: 0644
