---
# /roles/couchdb/defaults/main.yml
couchdb_version: 2.0.0
couch_data_dir: '{{ encrypted_root }}/couchdb2'
couch_backup_dir: "{{ encrypted_root }}/backups/couchdb2"
backup_couch: False
remote_couch_backup: False
couch_s3: False
couchdb_user: couchdb
couchdb_group: couchdb
couchdb_backup_days: 2
couchdb_backup_weeks: 2
couchdb_password_salt: "{{ inventory_hostname|hash('sha1') }}"
couchdb_httpd_auth_secret: "{{ ansible_product_uuid|hash('sha256') }}"
couchdb_instance_uuid: "{{ inventory_hostname|to_uuid }}"
